import { useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-gradient-to-b from-slate-950 to-black">
        <div className="container flex flex-col items-center gap-12 px-4 py-16">
          <h1>Welcome</h1>
          <p>Hello World</p>
        </div>
      </main>
    </>
  );
}
