////////////////////////////////////////////////////////////////
//What do we want included in the profile
//Name of the person
//What year they are (stored as an interger 1,2,3,4,5 (5 being a grad student))
//User BIO
//Classes they have and are signed up for
//Edit/submit profile and delete profile buttons
////////////////////////////////////////////////////////////////

import { UserProfile, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-800">
        <div className="container flex flex-col gap-12 px-4 py-16 ">
          <h1 className="text-4xl">Edit your profile</h1>
          <form className="flex flex-col gap-4">
            <div>
              <label htmlFor="name" className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
              Student Name
              </label>
              <input id="name" className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"/>
            </div>
            <div>
            <label htmlFor="aboutme" className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
              About Me
              </label>
              <textarea id="aboutme" className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"/>
            </div>
            <div>
            <label htmlFor="year" className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
            Year
              </label>
              <select id="year"  className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500">
                <option value="1">1 - Freshman</option>
                <option value="2">2 - Sophomore</option>
                <option value="3">3 - Junior</option>
                <option value="4">4 - Senior</option>
                <option value="5">5 - Graduate Student</option>
              </select></div>
            <button type="submit" className="mb-2 mr-2 rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
              Create
            </button>
          </form>
        </div>
      </main>
    </>
  );
}
